import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import "./styles/global.css";
import "./styles/app.css";
import { GistSyncProvider } from "@repus/gist-sync/react";
import { ThemeProvider } from "./lib/theme";
import { I18nProvider } from "./lib/i18n";
import { syncConfig, syncSchema, serialize, apply } from "./lib/sync";
import App from "./App";

// Follows are per-conference, so FollowProvider is mounted inside the conference
// layout (ConferenceLayout). Theme and GitHub-login/Gist-sync are site-wide, so
// they live here. GistSyncProvider syncs all conferences' follows via one gist.
createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <BrowserRouter>
      <ThemeProvider>
        <I18nProvider>
          <GistSyncProvider config={syncConfig} schema={syncSchema} serialize={serialize} apply={apply}>
            <App />
          </GistSyncProvider>
        </I18nProvider>
      </ThemeProvider>
    </BrowserRouter>
  </StrictMode>,
);

// Register the service worker (generated by scripts/build-sw.mjs) in production
// only, so the app is installable and works offline after the first visit. It
// auto-updates (skipWaiting + clientsClaim) on the next load. Dev has no SW.
if (import.meta.env.PROD && "serviceWorker" in navigator) {
  window.addEventListener("load", () => {
    navigator.serviceWorker.register("/sw.js").catch(() => {});
  });
}
